# Generated by Django 3.1.5 on 2021-01-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=12)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.FloatField()),
                ('fecha', models.DateTimeField(verbose_name='fecha de venta')),
            ],
        ),
        migrations.CreateModel(
            name='SanIng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwiches.ingrediente')),
                ('fk_sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwiches.sandwich')),
            ],
        ),
        migrations.CreateModel(
            name='CliSan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwiches.cliente')),
                ('fk_sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwiches.sandwich')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='fk_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sandwiches.venta'),
        ),
    ]
